# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='isDeveloper',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
