# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20170114_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isDeveloper',
            field=models.BooleanField(default=False),
        ),
    ]
