# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20170221_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channelparticipant',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Home.Channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Home.Channel'),
        ),
    ]
