# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20170114_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
