# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_channelparticipant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='created_at',
        ),
    ]
