# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20170204_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.ChannelParticipant'),
        ),
    ]
